apiVersion: v1
kind: Pod
metadata:
  name: loki
  labels:
    app: loki
spec:
  containers:
    - name: loki
      image: grafana/loki:2.7.3
      ports:
        - containerPort: 3100
  volumes:
    - name: loki-config-path
      hostPath: ./loki-config.yml
      path: /etc/loki/loki-config.yml
  command: ["-config.file=/etc/loki/loki-config.yml"]
