apiVersion: v1
kind: Pod
metadata:
  name: loki
  labels:
    app: loki
spec:
  volumes:
    - name: loki-config
      hostPath:
       path: /home/docker/
       type: FileOrCreate
  containers:
    - name: loki
      image: grafana/loki:2.7.3
      ports:
        - containerPort: 3100
      volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/
      command: ["-config.file=/etc/loki/loki-config.yml"]
