apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
  labels:
    app: ngiinx-proxy
spec:
  volumes:
    - name: nginx-logs
      hostPath:
       path: /var/log/nginx
       type: FileOrCreate
  containers:
    - name: nginx-proxy
      image: laurentbel/nginx-basic-auth
      ports:
        - containerPort: 80
      env:
        - name: FORWARD_HOST
          value: loki
        - name: FORWARD_PORT
          value: "3100"
        - name: BASIC_USERNAME
          value: xcenter
        - name: BASIC_PASSWORD
          value: xc3nt3rl1nx
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
