apiVersion: v1
kind: Pod
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  volumes:
    - name: promtail-config-path
      hostPath:
        path: ./promtail-config.yml
        type: FileOrCreate
    - name: promtail-logs
      hostPath:
        path: /var/log
        type: FileOrCreate
  containers:
    - name: promtail
      image: grafana/promtail:2.7.3
      volumeMounts:
        - name: promtail-config-path
          mountPath: /etc/promtail/
        - name: promtail-logs
          mountPath: /var/logs/
  command: ["-config.file=/etc/loki/loki-config.yml"]
